### ISSUE TITLE
Overriding target="_blank"

### ISSUE THREAD

**Issue by kaiofreitas** [sandoche/Producthunt-floating-prompt#4]
Hi.

Thanks for this project. Very useful!

I was wondering if there's a way to override the `target=_blank` attribute so I can use the prompt to redirect users to one of my own pages.

**Comment by sandoche** [comment]
Ah yeah it's something I forgot to do, feel free to fork the library to enable it, otherwise I'll do it later.

**Comment by sandoche** [comment]
I just added this feature @kaiofreitas
